### ISSUE TITLE
Erreur cpasbien

### ISSUE THREAD

**Issue by Lethtel** [Snipees/couchpotato.providers.french#10]
Bonjour tout le monde,

J'ai cette erreur semblable à mon VDD qui me revient :
[   couchpotato.core.event] Error in event "quality.single", that wasn't caught: Traceback (most recent call last):
  File "C:\Users\letht\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\event.py", line 15, in runHandler
  File "C:\Users\letht\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\plugins\quality\main.py", line 115, in single
  File "C:\Users\letht\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\CodernityDB\database_super_thread_safe.py", line 43, in _inner
  File "C:\Users\letht\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\CodernityDB\database.py", line 944, in get
RecordNotFound: Not found
encoding=cp1252 debug=False args=['--quiet'] app_dir=C:\Users\letht\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32 data_dir=C:\Users\letht\AppData\Roaming\CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x38d4e78> > options=Namespace(config_file='C:\Users\letht\AppData\Roaming\CouchPotato\settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='C:\Users\letht\AppData\Roaming\CouchPotato\couchpotato.pid', quiet=True) 

Du coup jamais rien qui télécharge sur couchpotato vu que je n'ai aucun résultat en retour.

Une idée ? :/

Vous remerciant

**Comment by Lethtel** [comment]
Solved with last PR
